apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tattoo-database
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:sant125/aws-devops.git
    targetRevision: HEAD
    path: manifests/database
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
